In [26]:
import numpy as np
def sigmoid(x):
    return 1/(1+np.exp(-x))
def sigmoid_derivative(x):
    return x*(1-x)

In [27]:
# datasets
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])   # 4X2 input
expected_output = np.array([[0],[1],[1],[0]])  # 4X1 output
print(inputs)
print(expected_output)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]


In [28]:
epochs = 100000
lr = 0.1
inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2,2,1

In [29]:
# Random weights and bias initialization
hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))
output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))

print("Initial hidden Weights: \n")
print(hidden_weights)                   # 2X2 
print("Initial output Weights: \n")
print(output_weights)                   #2X1

Initial hidden Weights: 

[[0.11849992 0.72043016]
 [0.19402817 0.68169964]]
Initial output Weights: 

[[0.10941586]
 [0.2099447 ]]


In [30]:
# Training algorithm
for i in range(epochs):
    # Forward Propagation
    hidden_layer_activation = np.dot(inputs,hidden_weights) # 4X2
    hidden_layer_output = sigmoid(hidden_layer_activation)  # 4X2
    
    output_layer_activation = np.dot(hidden_layer_output,output_weights)  # 4X1
    predicted_output = sigmoid(output_layer_activation)                   # 4X1
    
    # Back Propagation
    error = expected_output - predicted_output                         # 4X1
    d_predicted_output = error * sigmoid_derivative(predicted_output)  # 4X1
    
    error_hidden_layer = d_predicted_output.dot(output_weights.T)                 # 4X2
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output) # 4X2
    
    # Updating Weights and Biases
    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr # 2X1
    hidden_weights += inputs.T.dot(d_hidden_layer) * lr                  # 2X2
    
# print final weights
print("Final hidden weights: \n")
print(hidden_weights)

print("Final output weights: \n")
print(output_weights)

x = np.dot(inputs, hidden_weights)
x = sigmoid(x)
x = np.dot(x,output_weights)
final_output = sigmoid(x)

print("expected output after 10000 epochs \n")
print(final_output)

Final hidden weights: 

[[0.926699   7.72731331]
 [0.92669948 7.72758174]]
Final output weights: 

[[-33.21473443]
 [ 26.41726415]]
expected output after 10000 epochs 

[[0.03233502]
 [0.93152943]
 [0.93152943]
 [0.09131112]]
